service: sis-email-services

provider:
  name: aws
  runtime: nodejs10.x
  region: ${opt:region, 'eu-west-1'}

  stage: dev

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
      - "ses:SendEmail"
      Resource: "*"
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

  environment:
    email: ${file(./secret.json):email}
    password: ${file(./secret.json):password}

package:
  exclude:
    - node_modules/**
    - '!node_modules/node-fetch/**'
    - '!node_modules/nodemailer/**'

functions:
  email:
    handler: handler.email
    events:
    - http:
        path: email
        method: post
        cors: true
  email-node:
    handler: emailNode.emailNode
    events:
    - http:
        path: email/node
        method: post
        cors: true
# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
